// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddAccount(arg1:string):Promise<backend.Account>;

export function DeleteAccount(arg1:string):Promise<void>;

export function ListAccount():Promise<Array<backend.Account>>;

export function RefreshAccount():Promise<void>;
