// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['backend']['App']['AddAccount'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['backend']['App']['DeleteAccount'](arg1);
}

export function ListAccount() {
  return window['go']['backend']['App']['ListAccount']();
}

export function RefreshAccount() {
  return window['go']['backend']['App']['RefreshAccount']();
}
